from PyQt6 import QtWidgets
from PyQt6 import QtCore
from PyQt6 import QtGui
from src.usApp import autoservisPopis
from src.win import jednotliveAutoservisII
from vendor.rp import resource_path

class Ui_JedAutoser(jednotliveAutoservisII.Ui_JedAutoserII, object):
    def setupUi(self, Form, autoservis):
        """
        metoda pro vytvoreni prehledu autoservisu
        :param Form: form
        :param autoservis: id autoservisu
        :return: okno
        """
        Form.setObjectName("Form")
        Form.resize(450, 670)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lAutoservis = QtWidgets.QLabel(parent=Form)
        self.autoservis = autoservisPopis.AutoservisPopis.vytvorPrehled(autoservis)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lAutoservis.setFont(font)
        self.lAutoservis.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lAutoservis.setObjectName("lAutoservis")
        self.horizontalLayout_11.addWidget(self.lAutoservis)
        self.lOtevrenoZavreno = QtWidgets.QLabel(parent=Form)
        self.lOtevrenoZavreno.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lOtevrenoZavreno.setFont(font)
        self.lOtevrenoZavreno.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lOtevrenoZavreno.setObjectName("lOtevrenoZavreno")
        self.horizontalLayout_11.addWidget(self.lOtevrenoZavreno)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.layoutCelek = QtWidgets.QVBoxLayout()
        self.layoutCelek.setObjectName("layoutCelek")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.layoutCelek.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lPondeli = QtWidgets.QLabel(parent=Form)
        self.lPondeli.setObjectName("lPondeli")
        self.horizontalLayout_2.addWidget(self.lPondeli)
        self.layoutCelek.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lUtery = QtWidgets.QLabel(parent=Form)
        self.lUtery.setObjectName("lUtery")
        self.horizontalLayout_3.addWidget(self.lUtery)
        self.layoutCelek.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lStreda = QtWidgets.QLabel(parent=Form)
        self.lStreda.setObjectName("lStreda")
        self.horizontalLayout_4.addWidget(self.lStreda)
        self.layoutCelek.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        spacerItem3 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lCtvrtek = QtWidgets.QLabel(parent=Form)
        self.lCtvrtek.setObjectName("lCtvrtek")
        self.horizontalLayout_5.addWidget(self.lCtvrtek)
        self.layoutCelek.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(parent=Form)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        spacerItem4 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.lPatek = QtWidgets.QLabel(parent=Form)
        self.lPatek.setObjectName("lPatek")
        self.horizontalLayout_6.addWidget(self.lPatek)
        self.layoutCelek.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(parent=Form)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        spacerItem5 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.lSobota = QtWidgets.QLabel(parent=Form)
        self.lSobota.setObjectName("lSobota")
        self.horizontalLayout_7.addWidget(self.lSobota)
        self.layoutCelek.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(parent=Form)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem6 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.lNedele = QtWidgets.QLabel(parent=Form)
        self.lNedele.setObjectName("lNedele")
        self.horizontalLayout_8.addWidget(self.lNedele)
        self.layoutCelek.addLayout(self.horizontalLayout_8)
        self.label_13 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.layoutCelek.addWidget(self.label_13)
        self.layoutTel1 = QtWidgets.QHBoxLayout()
        self.layoutTel1.setObjectName("layoutTel1")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel1.addItem(spacerItem7)
        self.label_17 = QtWidgets.QLabel(parent=Form)
        self.label_17.setMaximumSize(QtCore.QSize(22, 22))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(resource_path("src/img/phone.png")))
        self.label_17.setScaledContents(True)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.layoutTel1.addWidget(self.label_17)
        spacerItem8 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel1.addItem(spacerItem8)
        self.lTel1 = QtWidgets.QLabel(parent=Form)
        self.lTel1.setObjectName("lTel1")
        self.layoutTel1.addWidget(self.lTel1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel1.addItem(spacerItem9)
        self.layoutCelek.addLayout(self.layoutTel1)
        self.layoutTel2 = QtWidgets.QHBoxLayout()
        self.layoutTel2.setObjectName("layoutTel2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel2.addItem(spacerItem10)
        self.label_18 = QtWidgets.QLabel(parent=Form)
        self.label_18.setMaximumSize(QtCore.QSize(22, 22))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(resource_path("src/img/phone.png")))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.layoutTel2.addWidget(self.label_18)
        spacerItem11 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel2.addItem(spacerItem11)
        self.lTel2 = QtWidgets.QLabel(parent=Form)
        self.lTel2.setObjectName("lTel2")
        self.layoutTel2.addWidget(self.lTel2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel2.addItem(spacerItem12)
        self.layoutCelek.addLayout(self.layoutTel2)
        self.layoutTel3 = QtWidgets.QHBoxLayout()
        self.layoutTel3.setObjectName("layoutTel3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel3.addItem(spacerItem13)
        self.label_19 = QtWidgets.QLabel(parent=Form)
        self.label_19.setMaximumSize(QtCore.QSize(22, 22))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(resource_path("src/img/phone.png")))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.layoutTel3.addWidget(self.label_19)
        spacerItem14 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel3.addItem(spacerItem14)
        self.lTel3 = QtWidgets.QLabel(parent=Form)
        self.lTel3.setObjectName("lTel3")
        self.layoutTel3.addWidget(self.lTel3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel3.addItem(spacerItem15)
        self.layoutCelek.addLayout(self.layoutTel3)
        self.layoutTel4 = QtWidgets.QHBoxLayout()
        self.layoutTel4.setObjectName("layoutTel4")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel4.addItem(spacerItem16)
        self.label_20 = QtWidgets.QLabel(parent=Form)
        self.label_20.setMaximumSize(QtCore.QSize(22, 22))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(resource_path("src/img/phone.png")))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.layoutTel4.addWidget(self.label_20)
        spacerItem17 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel4.addItem(spacerItem17)
        self.lTel4 = QtWidgets.QLabel(parent=Form)
        self.lTel4.setObjectName("lTel4")
        self.layoutTel4.addWidget(self.lTel4)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutTel4.addItem(spacerItem18)
        self.layoutCelek.addLayout(self.layoutTel4)
        self.layoutEmail = QtWidgets.QHBoxLayout()
        self.layoutEmail.setObjectName("layoutEmail")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutEmail.addItem(spacerItem19)
        self.label_21 = QtWidgets.QLabel(parent=Form)
        self.label_21.setMaximumSize(QtCore.QSize(22, 22))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(resource_path("src/img/email.png")))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.layoutEmail.addWidget(self.label_21)
        spacerItem20 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutEmail.addItem(spacerItem20)
        self.lEmail = QtWidgets.QLabel(parent=Form)
        self.lEmail.setObjectName("lEmail")
        self.layoutEmail.addWidget(self.lEmail)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutEmail.addItem(spacerItem21)
        self.layoutCelek.addLayout(self.layoutEmail)
        self.gridLayout.addLayout(self.layoutCelek, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.comboTypy = QtWidgets.QComboBox(parent=Form)
        self.comboTypy.setObjectName("comboTypy")
        for i in self.autoservis.seznamTypu:
            self.comboTypy.addItem("")
        self.horizontalLayout.addWidget(self.comboTypy)
        self.btnHledat = QtWidgets.QPushButton(parent=Form)
        self.btnHledat.setObjectName("btnHledat")
        self.horizontalLayout.addWidget(self.btnHledat)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem23)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lURLadresa = QtWidgets.QLabel(parent=Form)
        self.lURLadresa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lURLadresa.setObjectName("lURLadresa")
        self.verticalLayout_2.addWidget(self.lURLadresa)
        self.lUlice = QtWidgets.QLabel(parent=Form)
        self.lUlice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lUlice.setObjectName("lUlice")
        self.verticalLayout_2.addWidget(self.lUlice)
        self.lPSC = QtWidgets.QLabel(parent=Form)
        self.lPSC.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lPSC.setObjectName("lPSC")
        self.verticalLayout_2.addWidget(self.lPSC)
        self.lMesto = QtWidgets.QLabel(parent=Form)
        self.lMesto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lMesto.setObjectName("lMesto")
        self.verticalLayout_2.addWidget(self.lMesto)
        self.btnHledat.clicked.connect(self.hledatHledat)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


def spustitOkenko(object : object, autoservis):
    """
    metoda pro vytvoreni prehledu autoservisu
    :param object: form
    :param autoservis: id autoservisu
    :return: okno
    """
    object.Form = QtWidgets.QWidget()
    object.ui = Ui_JedAutoser()
    object.ui.setupUi(object.Form, autoservis)
    object.Form.show()



